slug: using-the-cluster-deploy-prometheus-grafana
id: msaqzhk7farx
title: How to set up Prometheus and Grafana on OpenShift
description: |
  ## Goal

  Learn how to use [Prometheus](https://github.com/prometheus/prometheus) on OpenShift to collect metrics from an application and then visualize the results with [Grafana](https://github.com/grafana/grafana).

  ## Concepts

  * Prometheus, exporters, and application metrics
  * Grafana charts and graphs
  * OpenShift Web Console
  * `oc` OpenShift command line tool

  ## Use case

  You can analyze application metrics to spot problems, monitor performance, audit resource use, and improve your understanding of your application's behavior in order to improve it.

  This OpenShift cluster will self-destruct in one hour.
icon: https://logodix.com/logo/1910931.png
level: beginner
tags:
- openshift
owner: openshift
developers:
- nvinto@redhat.com
- rjarvine@redhat.com
- cclyburn@redhat.com
- ryanj@redhat.com
checksum: "18272790957656568067"
