version: "2"
virtualmachines:
- name: crc-nonest-1
  image: openshift-instruqt/openshift-instruqt-crc490-211026
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
